### ISSUE TITLE
Geräte oder Variblen ID auswählen funktioniert nicht

### ISSUE THREAD

**Issue by kafibo** [ioBroker/ioBroker.text2command#102]
Adapter Version: 2.1.1
NPM: 6.14.12
Node js: 12.22.1

Wenn man nach anlegen einer neuen Regel eine Geräte bzw. Variablen ID auswählen möchte öffnet sich ein Popup wo man dann eigentlich die gewünschte ID auswählen kann, aber es dreht links oben nur der blaue Kreis und nichts passiert . Auch nach längeren warten nicht. Ich habe zwei Instanzen installiert und in beiden tritt derselbe Fehler auf.

**Comment by exitus27** [comment]
Das gleiche Problem habe ich auch egal welchen Browser ich nehme

**Comment by derandre24** [comment]
Hi,

ich habe das selbe Thema.

Adapter Version: 2.1.1
Node.js: v12.22.1
NPM: 6.14.12

**Comment by Proestkh** [comment]
HALLO, AUCH ICH HABE DIESES PROBLEM.
text2command Adapter Version 2.1.1
Node v12.22.1
NPM 6.14.12
js adapter  5.1.3

**Comment by derandre24** [comment]
Hier mal eine Lösung bis das Thema gefixt ist.
Mann kann die Einträge direkt in der objects.json ändern.
Am besten geht man hin und erstellt einen neuen Eintrag und speichert diesen ab. Im Anschluss stoppt man ioBroker, öffnet die objects.json und sucht nach seinem neuen Eintrag. Dann in etwa so aus.

"name":"Schalte irgendwas an oder aus"},{"words":"Garagentor","ack":"Das Garagentor wird bewegt.","args":["**sonoff.0.Garagentor.POWER**","true"],"_break":true,"template":"userDeviceControl"

Was hier Fett ist, fehlt bei eurem neuen Eintrag. Hier den Entsprechenden Aktor eintragen. 

Gruß André

**Comment by Proestkh** [comment]
Hallo, danke für die Mitteilung. 
Kannst du mir noch sagen mit welchem Editor ich die JSON Datei editieren kann.
Dank und Gruß 
Karl-Heinz 

Von meinem iPhone gesendet

**Comment by derandre24** [comment]
Ich habe mir die Datei auf den Mac gezogen und dort mit BBEdit bearbeitet. Unter Linux oder Windows würde ich Notepad++ nehmen. Zur Sicherheit benenne die alte Datei um und kopiere deine geänderte Datei. 

Gruß André

**Comment by Apollon77** [comment]
> HALLO, AUCH ICH HABE DIESES PROBLEM.

@Proestkh Und ne kaputte tastatir. Dein Caps-Lock klemmt scheinbar ;-)

@derandre24 Also bevr Ihr anfangt das objects.json zu editieren bitte per Admin das "system.adapter.text2command.0" Objekt editieren. Ist genau das gleiche

**Comment by KaHu85** [comment]
Selbes Problem!
Es ist auch ein Eintrag von einem User im ioborker Forum: [](https://forum.iobroker.net/topic/46458/docker-text2command-probleme-beim-ausw%C3%A4hlen-eines-skripts/3?loggedin=true)

Hoffe dass das Problem erruiert werden kann,

**Comment by PatrickDa87** [comment]
Habe dasselbe Problem.

text2command Adapter Version 2.1.1

**Comment by derandre24** [comment]
bei mir Funktioniert es, wenn ich auf die Version 2.1.0 zurück gehe.

**Comment by Proestkh** [comment]
Hallo André, wie komme ich von 2.1.1 auf 2.1.0
Sorry, bin kein Spezi, wäre nett, wenn Du mir helfen würdest.
Gruß 
Karl-Heinz

Von meinem iPhone gesendet

**Comment by derandre24** [comment]
> Hallo André, wie komme ich von 2.1.1 auf 2.1.0 Sorry, bin kein Spezi, wäre nett, wenn Du mir helfen würdest. Gruß Karl-Heinz Von meinem iPhone gesendet
> […](#)
> Am 27.07.2021 um 15:40 schrieb derandre24 ***@***.***>: ﻿ bei mir Funktioniert es, wenn ich auf die Version 2.1.0 zurück gehe. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi Karl-Heinz,

du musst an der Stelle wo du die Adapter installierst oben auf das Männlein mit dem Bauhelm klicken. Damit kommst du in den Experten Modus. Dann suchst du den Adapter "Text2Command" und klickst auf das "Eckige Plus"  ganz rechts hinter dem Adapter. Daraufhin öffnet sich ein Pop-up in dem du auswählen kannst welche Version du Installieren möchtest.

Gruß André

**Comment by Proestkh** [comment]
Super, funktioniert, vielen Dank.
Gruß Karl-Heinz 

Von meinem iPhone gesendet

**Comment by lord389** [comment]
Selbes Problem mir 2.1.1, ich bin zurück auf 2.1.0.

**Comment by ger-pakon** [comment]
Auch bei mir ist das Problem. Musste auch auf 2.1.0 zurück. Kann man irgendwie Debug-Informationen zum Fehler zukommen lassen?

**Comment by GermanBluefox** [comment]
Ich kann das Problem mit 2.1.7 nicht reproduzieren.
Wird was in der Browser Konsole gesagt?
