### ISSUE TITLE
Die Meldung "Ich verstehe nicht" per Einstellung aktivieren bzw. deaktivieren

### ISSUE THREAD

**Issue by hgschiller** [ioBroker/ioBroker.text2command#105]
Wenn man einen Text eingibt der zu keiner Antwort führt, kommt die Meldung:

Ich verstehe "Hallo ich bin das" nicht

Es wäre nicht schlecht, wenn man diese Meldung aktivieren und deaktivieren könnte z.B. in den Einstellungen.

**Comment by GermanBluefox** [comment]
IN 2.1.8
![image](https://user-images.githubusercontent.com/4582016/154946222-fe44033a-85d2-41dc-a5be-a5cf52aa585b.png)

**Comment by hgschiller** [comment]
Muss ich vorher noch was löschen oder wo anders eintragen ?
Bei mir ist die Option unter Einstellungen zwar da, ich kann sie aber nicht aktivieren. Hinzu komm, das diese Option, obwohl sie nicht aktiviert ist, aktiv ist, denn ich bekomme diesen Satz auf Telegram nicht mehr angezeigt ! 
Was mache ich verkehrt ?

**Comment by GermanBluefox** [comment]
Please retest with 3.0

**Comment by hgschiller** [comment]
Jetzt funktioniert es, wenn man es einmal aktiviert und dann wieder deaktiviert ! 
Danach läuft es prima ! Danke.
