### ISSUE TITLE
Runden von Werten bei der Ausgabe

### ISSUE THREAD

**Issue by matthiasisrael** [ioBroker/ioBroker.text2command#118]
Zur Ausgabe von akt. Verbräuchen (Strom / Wasser) über Alexa wäre es toll, wenn Zahlen auf eine bestimmte Anzahl von Nachkommastellen gerundet werden könnten.
Leider funktioniert bei mir der Weg über die Temperaturabfrage nicht, wo die Zahl in integer umgewandelt wird...

**Comment by GermanBluefox** [comment]
IMplemented in 2.1.8
