### ISSUE TITLE
Not open UI after update to 2.1.2

### ISSUE THREAD

**Issue by paveltsytovich** [ioBroker/ioBroker.text2command#126]
**White page when I try to open UI of this adapter**  

**To Reproduce**  
1. Go to 'Text to command ' link
2. See white screen

**Expected behavior**  
Show UI

**Screenshots & Logfiles**  

In console.log of javascript

![image](https://user-images.githubusercontent.com/1669930/154029459-8c657347-950e-46a0-b9d8-33bd846c8128.png)

**Versions:**  
 - Adapter version: 2.1.2
 - JS-Controller version: 3.3.22
 - Node version: 14.19.0
 - Operating system: Rapberrian 32bit

**Comment by MarkSau** [comment]
Habe das gleiche Problem..mit Downgrade auf 2.1.1 funktioniert es wieder

**Comment by paveltsytovich** [comment]
> Habe das gleiche Problem..mit Downgrade auf 2.1.1 funktioniert es wieder

No work after downgrade to 2.1.1 and 2.1.0

**Comment by Sefina-DS** [comment]
Gleiche Problem, 1x öffnen geht es dann egal welche Version kommt das gleiche Bild.
Ich muss den Adapter aber deinstallieren und neu installieren das er die WebGui aufrufft.

MfG

**Comment by paveltsytovich** [comment]
> Please check the latest 2.1.6

Yes, work fine. Many thanks
