### ISSUE TITLE
Einstellungen unter Instanzen ist ausgegraut

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.text2command#16]
Admin 3.3.5
text2command 1.1.7

node 8
npm 4

Die Einstellungen des Adapters sind ausgegraut.

Wollte die Funktion text processing einstellen.

<img width="447" alt="text2command" src="https://user-images.githubusercontent.com/11463809/38577342-e5810d8c-3d00-11e8-9691-d1928c6ba0f9.png">

**Comment by GermanBluefox** [comment]
Es gibt keine Einstellungen. Man muss über Menü Links die Rules anlegen.

вт, 10 апр. 2018 г., 20:51 Michael <notifications@github.com>:
