### ISSUE TITLE
Parsing error in Version 1.2.1?

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.text2command#17]
Hallo,
nach Update auf V1.2.1 bekomme ich folgende Fehlermeldungen:

![grafik](https://user-images.githubusercontent.com/35137293/39373656-8cd51f98-4a48-11e8-859d-c0f2b98d4442.png)

Nach Downgrade auf V1.2.0 ist wieder alles OK.

**Comment by GermanBluefox** [comment]
Fixed

**Comment by Steff42** [comment]
Thx for the fast fixing, V1.2.2 works fine!
