### ISSUE TITLE
Alexa custom skill crashes cloud and text2command instances

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.text2command#18]
cloud.0 | 2018-05-05 08:49:26.027 | error | at Timer.listOnTimeout (timers.js:266:5)
-- | -- | -- | --
cloud.0 | 2018-05-05 08:49:26.027 | error | at tryOnTimeout (timers.js:306:5)
cloud.0 | 2018-05-05 08:49:26.027 | error | at ontimeout (timers.js:471:11)
cloud.0 | 2018-05-05 08:49:26.027 | error | at Timeout.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/iobroker.cloud/lib/alexaCustom.js:159:42)
cloud.0 | 2018-05-05 08:49:26.027 | error | at AlexaCustom.processAfter (/opt/iobroker/node_modules/iobroker.cloud/lib/alexaCustom.js:43:50)
cloud.0 | 2018-05-05 08:49:26.027 | error | TypeError: Cannot read property 'value' of undefined
cloud.0 | 2018-05-05 08:49:26.027 | error | uncaught exception: Cannot read property 'value' of undefined
text2command.0 | 2018-05-05 08:49:25.034 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
text2command.0 | 2018-05-05 08:49:25.034 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:233:12)
text2command.0 | 2018-05-05 08:49:25.034 | error | at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:275:10)
text2command.0 | 2018-05-05 08:49:25.034 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
text2command.0 | 2018-05-05 08:49:25.034 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
text2command.0 | 2018-05-05 08:49:25.034 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3400:34)
text2command.0 | 2018-05-05 08:49:25.034 | error | at Adapter.emit (events.js:210:7)
text2command.0 | 2018-05-05 08:49:25.034 | error | at emitOne (events.js:115:13)
text2command.0 | 2018-05-05 08:49:25.034 | error | at Adapter. (/opt/iobroker/node_modules/iobroker.text2command/main.js:85:21)
text2command.0 | 2018-05-05 08:49:25.034 | error | at processText (/opt/iobroker/node_modules/iobroker.text2command/main.js:183:23)
text2command.0 | 2018-05-05 08:49:25.034 | error | TypeError: Cannot create property 'language' on string 'directCommunication fernseher an ist'
text2command.0 | 2018-05-05 08:49:25.028 | error | message messagebox.system.adapter.text2command.0 [object Object] Cannot  create property 'language' on string 'directCommunication fernseher an  ist'

**Comment by Apollon77** [comment]
please test Github version

**Comment by Apollon77** [comment]
1.2.4 released
