### ISSUE TITLE
Update von 2.3.0 auf 3.0.0

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.text2command#204]
Nach dem Update bleibt die Seite ( tab ) von Text zu Kommandos leer bei Instanz .0
Ich habe eine weitere Instanz mit .1 und dort wird die Seite korrekt anzeigt.

Cache habe ich vom Browser geleert.
iob fix wurde ausgeführt.

Keine auffälligen Log Meldungen.

**Versions:**  
 - Adapter version: 3.0.0
 - JS-Controller version: 4.0.24
 - Node version: 16.19.1
 - Operating system: Linux Debian x64

**Comment by TeNNo2k5** [comment]
Habe das gleiche verhalten nach dem Update, testweise eine zweite Instanz installiert und es wird auch die Seite korrekt angezeigt.

- Adapter version: 3.0.0
- JS-Controller version: v6.2.0
- Node.js v16.19.0
- Operating system: Linux Ubuntu x64

**Comment by GermanBluefox** [comment]
> Nach dem Update bleibt die Seite ( tab ) von Text zu Kommandos leer bei Instanz .0 Ich habe eine weitere Instanz mit .1 und dort wird die Seite korrekt anzeigt.
> 
> Cache habe ich vom Browser geleert. iob fix wurde ausgeführt.
> 
> Keine auffälligen Log Meldungen.
> 
> **Versions:**
> 
> * Adapter version: 3.0.0
> * JS-Controller version: 4.0.24
> * Node version: 16.19.1
> * Operating system: Linux Debian x64

https://www.iobroker.net/#de/documentation/faq/_040_contibution.md?fehlerindergrafischeoberflchemelden

**Comment by TeNNo2k5** [comment]
![Unbenannt](https://user-images.githubusercontent.com/33666714/220072807-8514dc92-903c-4c98-8b1c-06f229ebe3d6.PNG)


bootstrap.jsx:19 iobroker.admin@6.3.6
instrument.ts:124 [2023-02-20T09:52:37.068Z] Try to connect
instrument.ts:124 Stored version: , new version: 6.3.6
instrument.ts:124 Connected: true
index.js:18 iobroker.text2command@3.0.0 using theme "dark"
Prompt.js:15 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:16 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:17 Help us to create open source project with reactJS!
Prompt.js:18 See you :)
socket.io.js:66 [2023-02-20T09:52:38.803Z] Try to connect
A bad HTTP response code (404) was received when fetching the script.
serviceWorker.js:63 Error during service worker registration: TypeError: Failed to register a ServiceWorker for scope ('https://192.168.178.201:8081/adapter/text2command/') with script ('https://192.168.178.201:8081/adapter/text2command/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.
(anonymous) @ serviceWorker.js:63
Promise.catch (async)
l @ serviceWorker.js:62
(anonymous) @ serviceWorker.js:122
load (async)
(anonymous) @ serviceWorker.js:106
(anonymous) @ index.js:46
(anonymous) @ index.js:46
(anonymous) @ index.js:46
Layout.js:417 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at Layout.js:417:27
    at Array.map (<anonymous>)
    at Layout.js:405:40
(anonymous) @ Layout.js:417
(anonymous) @ Layout.js:405
Promise.then (async)
value @ Layout.js:64
Hs @ react-dom.production.min.js:261
Ms @ react-dom.production.min.js:260
gs @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
xl @ react-dom.production.min.js:281
cl @ react-dom.production.min.js:270
V @ scheduler.production.min.js:13
Z @ scheduler.production.min.js:14

**Comment by GermanBluefox** [comment]
> Layout

Das ist schon VIEL besser. Damit ich noch den Fehler beseitigen kann, brauche ich noch dieses Object:
![image](https://user-images.githubusercontent.com/4582016/220331751-4ec49d57-76ab-4ef8-b58a-2cf9c0e8c23c.png)

Als JSON.

**Comment by TeNNo2k5** [comment]
`      "rules": [
        {
          "template": "userQuery",
          "_break": true,
          "words": "lampe wohnzimmer/wz status",
          "ack": "Lampe an? = %s",
          "args": [
            "sonoff.0.S20 - Steckdose Wohnzimmer.POWER"
          ],
          "id": "ddbcf846-fb97-45e7-9049-529ebdb90dcc",
          "name": "Fragen über irgendwas"
        },
        {
          "template": "userDeviceControl",
          "_break": true,
          "words": "lampe wohnzimmer/wz an",
          "ack": "Wohnzimmer Lampe wurde eingeschaltet",
          "args": [
            "sonoff.0.S20 - Steckdose Wohnzimmer.POWER",
            "true"
          ],
          "id": "fcf841f8-85db-4210-8149-5f3bd974ae69",
          "name": "Schalte irgendwas an oder aus"
        },
        {
          "template": "userDeviceControl",
          "_break": true,
          "words": "lampe wohnzimmer/wz aus",
          "ack": "Wohnzimmer Lampe wurde ausgeschaltet",
          "args": [
            "sonoff.0.S20 - Steckdose Wohnzimmer.POWER",
            "false"
          ],
          "id": "0d9997f7-4df0-48c9-b1bb-300c48c40aac",
          "name": "Schalte irgendwas an oder aus"
        },
        {
          "words": "übersicht/info/button/menu/menü",
          "ack": "",
          "args": [
            "javascript.0.scriptEnabled.Scripts.Javascript.Telegram_Buttons",
            "true"
          ],
          "_break": true,
          "template": "userDeviceControl",
          "name": "Schalte irgendwas an oder aus",
          "id": "88fa4f21-6da6-4ee0-af00-4de2ea138dca"
        },
        {
          "template": "whatTimeIsIt",
          "_break": true,
          "words": "zeit/spät/spaet",
          "id": "6e346c10-30f1-4d34-9732-72dd06f3ba7b",
          "name": "Wie spät ist es?"
        },
        {
          "template": "insideTemperature",
          "_break": true,
          "words": "intern/drin kalt/warm/temperatur",
          "ack": "Die Innentemperatur beträgt %s %u",
          "args": [
            "sonoff.0.WeMos D1 mini DHT11.DHT11_Temperature"
          ],
          "id": "41747739-32fd-41ae-b1bb-81f4d0f99d19",
          "name": "Wie kalt/warm ist es drin?"
        },
        {
          "template": "userQuery",
          "_break": true,
          "words": "status",
          "ack": "Ist die Lampe an: %s",
          "args": [
            "sonoff.0.S20 - Steckdose Wohnzimmer.POWER"
          ],
          "id": "2db2ce74-cb0f-40d3-9e09-71ce4bf98158",
          "name": "Fragen über irgendwas"
        },
        {
          "template": "userDeviceControl",
          "_break": true,
          "words": "PC Starten",
          "ack": "Pc wird gestartet",
          "args": [
            "javascript.0.WSTS01",
            "true"
          ],
          "id": "1f6eb036-91e2-4e01-98f7-15f01c637619",
          "name": "Schalte irgendwas an oder aus"
        },
        {
          "template": "sendText",
          "_break": true,
          "words": "ping",
          "ack": "Pinge %s",
          "args": [
            "javascript.0.ping",
            "%s"
          ],
          "id": "a6b8b853-3091-4f9e-b771-b74108140929",
          "name": "Schreibe Text in den Zustand"
        },
        {
          "template": "sendText",
          "_break": true,
          "words": "cmd",
          "ack": "Führe Kommando aus: %s",
          "args": [
            "javascript.0.cmd",
            "%s"
          ],
          "id": "3b5ca5a3-8329-4195-98d6-ecddfe5acee1",
          "name": "Schreibe Text in den Zustand"
        },
        {
          "template": "userDeviceControl",
          "_break": true,
          "words": "webcam",
          "ack": "",
          "args": [
            "javascript.0.webcam",
            "true"
          ],
          "id": "2550f839-0101-4f9a-8d05-fe9548773bf4",
          "name": "Schalte irgendwas an oder aus"
        },
        {
          "template": "sendText",
          "_break": true,
          "words": "shutdown",
          "ack": "",
          "args": [
            "javascript.0.net_rpcShutdown",
            "%s"
          ],
          "id": "66dacbce-d27f-4227-a10a-7d25b628e0a3",
          "name": "Schreibe Text in den Zustand"
        },
        {
          "template": "sendText",
          "_break": true,
          "words": "wol",
          "args": [
            "javascript.0.WakeOnLan",
            "%s"
          ],
          "ack": "",
          "id": "0281abb0-ef8e-4929-b6c3-f1dce53ba615",
          "name": "Schreibe Text in den Zustand"
        },
        {
          "template": "userDeviceControl",
          "_break": true,
          "words": "robo start",
          "ack": "Starte Reinigung",
          "args": [
            "mihome-vacuum.0.control.start",
            "true"
          ],
          "id": "c2ba1d37-657c-489c-86eb-6a4efe0810fa",
          "name": "Schalte irgendwas an oder aus"
        },
        {
          "template": "userDeviceControl",
          "_break": true,
          "words": "robo stop",
          "ack": "Robo Pause",
          "args": [
            "mihome-vacuum.0.control.pause",
            "true"
          ],
          "id": "0414f274-6f02-4678-b511-653311e9b919",
          "name": "Schalte irgendwas an oder aus"
        },
        {
          "words": "tanken",
          "ack": "",
          "args": [],
          "_break": true,
          "template": "buildAnswer",
          "name": "Antwort erzeugen",
          "id": "be0c6aab-a746-4f6a-ae92-ff43f6625a52"
        },
        {
          "words": "sprit",
          "ack": "",
          "args": [],
          "_break": true,
          "template": "buildAnswer",
          "name": "Antwort sprit",
          "id": "8186fab8-0a68-499e-8534-e83527b4ad70"
        }
      ],
`

**Comment by GermanBluefox** [comment]
> "rules": [
>         {
>           "template": "userQuery",
>           "_break": true,

Danke. Ich konnte das Problem fixen.

**Comment by TeNNo2k5** [comment]
@GermanBluefox 

Bestätige das mit v3.0.1 die text2command page wieder wie gewohnt angezeigt wird danke.
