### ISSUE TITLE
Binding mit .ts und .lc funktioniert nicht.

### ISSUE THREAD

**Issue by getriebesand** [ioBroker/ioBroker.text2command#22]
Scheinbar funktioniert .lc und .ts nicht. Welche man benötigt um die letzte Änderungszeit des Datenpunktes mitzuschicken.

**Comment by Apollon77** [comment]
Do you have an exact example of a configuration that do not work and what you expect?

**Comment by getriebesand** [comment]
Yes.
I want to ask "wie warm ist es im Gewächshaus"

ObjectID is set to mqtt.0.gewaechshaus.temperature1

this Answer works:
%s %u und {mqtt.0.gewaechshaus.humidity1}% Luftfeuchte
35.9 Grad und 29.6% Luftfeuchte

but I want to know the last change time of this value

this Answer doesn't work:
%s %u und {mqtt.0.gewaechshaus.humidity1}% Luftfeuchte - {mqtt.0.gewaechshaus.temperature1.lc; date('DD.MM.YYYY hh::mm')}

and this is logged:
"text2command.0" this.formatDate is not a function

I have testet .lc and .ts nothing works. And I can'T find the position in source code where this will be used.

**Comment by GermanBluefox** [comment]
Bis jetzt wurden Zeitfunktionen nicht implementiert

вт, 3 июл. 2018 г., 10:11 swash <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Fixed
