### ISSUE TITLE
Issues with values %s and %u

### ISSUE THREAD

**Issue by Pilzbauer90** [ioBroker/ioBroker.text2command#25]
Hello everyone,
I have a small problem with getting values to send.
I try to get the room temperature and the humanity send back by telegram.
The problem now is that I get the degree and the % sign but not the value itself.
![grafik](https://user-images.githubusercontent.com/36999810/45931237-89da6f80-bf6b-11e8-9728-50d59e0d61d2.png)
With this setting, I get the degree responded
Like "Im Schlafzimmer sind es °C" 
When I set parameter and text both to %u or %s I didn't get anything.
Maybe someone can help me

**Comment by Apollon77** [comment]
Simply have nothing in "Wert zum Schreiben"!! You do not want to change something.
