### ISSUE TITLE
Zeilenumbruch in "Quittungstext"

### ISSUE THREAD

**Issue by morgi1990** [ioBroker/ioBroker.text2command#28]
Im Quittungstext scheint es nicht möglich zu sein einen Zeilenumbruch einzugeben

Der im Forum zu findende "\n" scheint nur in Scripten zu funktionieren.

Oder gibt es einen anderen Weg um Zeilenumbrüche einzugeben?

**Comment by raidsec** [comment]
+1

**Comment by dervitti** [comment]
+1

**Comment by Pendora2017** [comment]
+1
