### ISSUE TITLE
Mobil devices and no trigger word

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.text2command#31]
When I open the text2commad tab on my tablet I can't see the trigger word. It's an 8 inch display. It's possible to optimize for mobile devices?

**Comment by Brainbug01** [comment]
Screenshot:

![screenshot_2018-12-07-21-05-32-266_com android chrome](https://user-images.githubusercontent.com/35106961/49670165-09081b80-fa64-11e8-8391-f0240d38c6a4.png)

**Comment by andre1974** [comment]
Same problem here.
Useless til it is fixed.

**Comment by deify** [comment]
This is happening on my mobile Android device using chrome and also on my Linux PC using chrome. It's not just limited to mobile devices

**Comment by klein0r** [comment]
Same here, this is not related to mobile devices - just to small screens.
When using a smaller browser window on my desktop (e.g. 1000px) the column is also missing.

**Comment by Brainbug01** [comment]
Works with V 2.0.2
