### ISSUE TITLE
Punkte in Werten werden falsch vorgelesen

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.text2command#32]
Wenn man sich einen Wert wie z.B. "21.6" ansagen lässt, wird dieser als "einunzwanzigster sechs" vorgelesen. Es sollte eine Option geben, dass dies dann (z.B. mit einem anderen Platzhalter als %s (danke an Apollo für den Vorschlag)) als "Einundzwanzig komma sechs" vorgelesen wird.
Das Problem tritt z.B. bei Temperaturwerten auf.

**Comment by do1osc** [comment]
Gibt es zu diesem Thema schon ein weiteres Vorgehen, bzw. eine Lösung ?

**Comment by Apollon77** [comment]
Das ganze ist denke ich nicht soooo simpel. Ob Komma oder Punkt ist sogar Sprachabhängig. Was auf jeden Fall geht ist ein Zwischenstate mit einem Skript zu nutzen um so etwas umzuformatieren.

**Comment by do1osc** [comment]
> Das ganze ist denke ich nicht soooo simpel. Ob Komma oder Punkt ist sogar Sprachabhängig. Was auf jeden Fall geht ist ein Zwischenstate mit einem Skript zu nutzen um so etwas umzuformatieren.

Okay, aber mit einem zusätzlichen Datenobjekt, in dem ich den Punkt in Komma ändere gibt das Text2Command immer NaN zurück, anstatt den Wert. Eine Konvertierung von "5,6" in eine Number hilt dabei auch nicht...
Also: 
Input ist Number "5.6" -> Konvertiert nach String als "5,6" -> ergibt NaN.
Input ist Number "5.6" -> Konvertiert nach String als "5,6" -> Konvertiert nach Number -> ergibt NaN.

Was übersehe ich ?

Mit freundlichen Grüßen Sven

**Comment by do1osc** [comment]
> > Das ganze ist denke ich nicht soooo simpel. Ob Komma oder Punkt ist sogar Sprachabhängig. Was auf jeden Fall geht ist ein Zwischenstate mit einem Skript zu nutzen um so etwas umzuformatieren.
> 
> Okay, aber mit einem zusätzlichen Datenobjekt, in dem ich den Punkt in Komma ändere gibt das Text2Command immer NaN zurück, anstatt den Wert. Eine Konvertierung von "5,6" in eine Number hilt dabei auch nicht...
> Also:
> Input ist Number "5.6" -> Konvertiert nach String als "5,6" -> ergibt NaN.
> Input ist Number "5.6" -> Konvertiert nach String als "5,6" -> Konvertiert nach Number -> ergibt NaN.
> 
> Was übersehe ich ?
> 
> Mit freundlichen Grüßen Sven

Problem erkannt und gelöst::
Der Zwischenstate darf keine Einheit haben.

**Comment by GermanBluefox** [comment]
Sollte im 2.0.3 unterstützt werden.
