### ISSUE TITLE
Fix code for .ts,lc.ack and fix multiple objects in simpleControl

### ISSUE THREAD

**Issue by dirkhe** [ioBroker/ioBroker.text2command#33]
Ich schreib mal auf deutsch...

Mir ist aufgefallen, dann man bei Antwort erzeugen ( und ich denke genrell beim Quittungstext) zum einen immer nur der value eines Objectes ausgegeben werden kann. Des weiteren habe ich auch immer nur ein Object aufgelöst bekommen, wenn ich folgenden Quittungstext eingegeben habe:
`Der Trockner ist aktuell {#Keller.0.Trockner.State;array(aus,an,läuft)} seit {#Keller.0.Trockner.State.ts;date(hh:mm)}`

Ich habe mir daraufhin den code mal angeschaut und habe mal einen patch Vorschlag. Bei mir funktioniert es damit.
[simpleControl.patch.txt](https://github.com/ioBroker/ioBroker.text2command/files/2705246/simpleControl.patch.txt)

Ich denke Issue #22 würde damit auch funktionieren

Gruss
Dirk

**Comment by GermanBluefox** [comment]
Fixed now
