### ISSUE TITLE
Javascripte können nicht ausgewählt werden

### ISSUE THREAD

**Issue by msiemers** [ioBroker/ioBroker.text2command#35]
Leider können keine Javascripte mehr ausgewählt werden. Bei einer Installation mit einer Javascript Version 4.06. fehlt der Abschnitt Javascripte in der Objektauswähl gänzlich. Vermutlich wurde bei den Scripten das Expert Flag hinterlegt. Leider gibt es in Text2Command keine Möglichkeit die Scripte mit diesem Flag einzubinden.
![2018-12-29 00_10_44-text2command-0 - iobroker](https://user-images.githubusercontent.com/34999079/50530481-58d78100-0afe-11e9-8d9f-f3a540489171.png)
![2018-12-29 00_11_03-objects - iobroker](https://user-images.githubusercontent.com/34999079/50530482-5bd27180-0afe-11e9-8784-097fbb7364b5.png)

**Comment by LordDuplo** [comment]
Hallo,

ich habe das selbe Problem. Es lassen sich keine Javascripte starten, da diese nicht angezeigt werden. Somit für mich zur Zeit leider unbrauchbar

**Comment by GermanBluefox** [comment]
Fixed in 2.0.2
