### ISSUE TITLE
Schreibe Text in den Zustand keine Funktion

### ISSUE THREAD

**Issue by elzershark** [ioBroker/ioBroker.text2command#38]
Schreibe Text in den Zustand funktioniert nicht. Alexa gibt keine Antwort und es wird auch kein Wert reingeschrieben.
Manuell funktioniert es

**Comment by Apollon77** [comment]
Bitte Adapter auf Debug und log hinzufügen

**Comment by elzershark** [comment]
Hätte ich gemacht. Bring nichts da absolut nichts bei diesem Befehl angezeigt wird. Weder im Log, noch unter Objekte, noch im iot oder sonst wo. Nur bei allen anderen "Befehlen" wird was eingetragen.. wenn es funzt, oder etwas nicht verstanden wird. Bei "Schreibe Text" passiert aber gar nichts. Auch keine Aussprache oder sonstwas

**Comment by elzershark** [comment]
Zufall.. raus gefunden was los ist..
Unter "Trigger Worte" wird das geschrieben auf was gehört werden soll.
Beispiel "schreibe text"
Rest normal verknüpfen.
Wenn man jetzt den Trigger sagt, passiert nichts. Und zwar deswegen:
Das Script führt alles von hinten nach vorne aus. Deswegen funzt nichts. So funtz es:
"Alexa, frage iobroker "das Haus" "schreibe Text"
Antwort: "geschrieben wurde "Haus das"
Im Objekt steht: "Haus das"

**Comment by elzershark** [comment]
b.z.w. das ist so konfus.. Man muss es selber ausprobieren um es zu fixen. 1 Wort geht, 2 wörter nicht. der, die, das, funzt. zahlen nicht. u.s.w.
Daher geben logs kein Sinn

**Comment by kruemelinger** [comment]
Mit diesem Problem kämpfe ich auch gerade.

Die ganzen Spracheingaben von Alexa kommen Wort für Wort von hinten nach vorne an. Warum?

**Comment by Apollon77** [comment]
Bitte zeigt doch mal Debug log ... und ja da gibt es log weiss ich.

Debug Log bei der Instanz aktivieren (Instanzen - expertenmodus - spalöte logstufe). Dann text sagen dann log zeigen

Und falls die Frage ist warm beim "custom Skill" der text nicht in der korrerkten reihenfolge wie gesprochen kommt dann lioegt das daran wie das ganze verarbeitet werden kann. eine "wirklich freie texterfassung" gibt es nicht so wirklich

**Comment by GermanBluefox** [comment]
Closed, because too old

**Comment by kruemelinger** [comment]
Hallo, 

bin leider jetzt erst wieder zum Basteln am iobroker gekommen. Hab gerade die neuste Version von text2command (2.0.3) installiert und probiert ob der Fehler vielleicht schon behoben ist bevor ich nochmal schreibe. Leider besteht der Fehler mit Alexa immer noch. Die einzelnen Wörter werden irgendwo "wild" umsortiert, und dadurch steht der Wert nicht mehr hinter dem Schlüsselwort hinter dem er stehen sollte. 

Vielleicht lässt sich da ja doch noch irgendwas machen...

Beim Satz "Alexa, sage iobroker stelle Bewegungsmelder im Bad auf 2". Als Wert wurde dann "stelle" eingetragen.

Hier mein Debug Log 

```
text2command.0 | 2020-07-16 07:45:46.307 | debug | (195410) system.adapter.admin.0: logging true
text2command.0 | 2020-07-16 07:45:29.077 | debug | (195410) sendTo "send" to system.adapter.iot.0 from system.adapter.text2command.0
text2command.0 | 2020-07-16 07:45:29.072 | info | (195410) Response: Bewegungsmelder ist auf stelle gestellt
text2command.0 | 2020-07-16 07:45:29.058 | info | (195410) Say ID 0_userdata.0.Bad.Dauer: stelle
text2command.0 | 2020-07-16 07:45:29.049 | debug | (195410) Words: ["bewegungsmelder",["bad","badezimmer"],"auf"]
text2command.0 | 2020-07-16 07:45:29.043 | info | (195410) processText: "controlDevice ? bad bewegungsmelder auf stelle"
text2command.0 | 2020-07-16 07:44:55.769 | info | (195410) starting. Version 2.0.3 in /opt/iobroker/node_modules/iobroker.text2command, node: v10.20.1, js-controller: 3.1.6
```

Bei "Alexa, sage iobroker Bewegungsmelder bad auf 2" wird kein wert eingetragen.

```
text2command.0 | 2020-07-16 07:57:33.927 | debug | (195410) sendTo "send" to system.adapter.iot.0 from system.adapter.text2command.0
text2command.0 | 2020-07-16 07:57:33.926 | info | (195410) Response: Bewegungsmelder ist auf gestellt
text2command.0 | 2020-07-16 07:57:33.918 | info | (195410) Say ID 0_userdata.0.Bad.Dauer:
text2command.0 | 2020-07-16 07:57:33.917 | debug | (195410) Words: ["bewegungsmelder",["bad","badezimmer"],"auf"]
text2command.0 | 2020-07-16 07:57:33.915 | info | (195410) processText: "controlDevice bewegungsmelder 2 bad auf"
```

Bei "Alexa, sage iobroker a Bewegungsmelder b bad c auf d 2"

```
text2command.0 | 2020-07-16 08:11:09.928 | debug | (195410) sendTo "send" to system.adapter.iot.0 from system.adapter.text2command.0
text2command.0 | 2020-07-16 08:11:09.927 | info | (195410) Response: Bewegungsmelder ist auf A gestellt
text2command.0 | 2020-07-16 08:11:09.917 | info | (195410) Say ID 0_userdata.0.Bad.Dauer: A
text2command.0 | 2020-07-16 08:11:09.916 | debug | (195410) Words: ["bewegungsmelder",["bad","badezimmer"],"auf"]
text2command.0 | 2020-07-16 08:11:09.914 | info | (195410) processText: "askDevice B auf D2 bad C bewegungsmelder A"
text2command.0 | 2020-07-16 08:11:03.301 | debug | (195410) system.adapter.admin.0: logging true

```

Alexa hat laut Sprachaufnahmen-Verlauf in der App auch alles richtig verstanden.
