### ISSUE TITLE
Cloud Zugriff erzeugt parallel laufenden text2command Prozess

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.text2command#40]
Hi,
wenn ich über den Cloud Zugriff text2command öffne sind sämtliche Befehle weg die ich eingepflegt habe.
Wenn ich dann welche neu anlege sind alle alten Befehle weg, auch wenn ich mich wieder lokal einlogge.

Beschrieben hier: https://forum.iobroker.net/viewtopic.php?p=227693#p227693

Und auch reproduzierbar. Logs hab ich auch oben im Forum gepostet.

**Comment by Apollon77** [comment]
Ich tippe das irgendwie die States nicht empfangen werden können wo die Daten drin stehen -  oder nicht lange genug gewartet wird?

**Comment by martinschm** [comment]
Hi,
beim JavaScript Adapter muss ich auch immer ein paar Sekunden warten. Hab bei text2command ebenfalls etliche Sekunden gewartet.

Knapp 20 Kommandos sind ja jetzt nicht so viele Daten und deutlich weniger vermutlich als eine ähnliche anzahl von Skripten. Evtl müsste man eine Sperre einbauen die Eingaben verhindert solange noch Daten geladen werden, oder einfach andere Befehle dann später unten anfügt.

**Comment by GermanBluefox** [comment]
Sollte jetzt gehen.
