### ISSUE TITLE
Alexa verdreht die Frage und versteht nicht

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.text2command#43]
Wenn ich sage "Alexa frage iobroker wie kalt ist es draussen" bekomme ich zur Antwort
Ich verstehe "kalt ist draussen es" nicht

**Comment by Apollon77** [comment]
Per Custom Skill? Dann ist das absolut ok so und sollte auch per Text2Command problemlos verarbeitbar sein weil die Reihenfolge der Begriffe egal ist und es um das Vorkommen geht. Was exakt ist Das problem?

**Comment by Apollon77** [comment]
Bzw: Wie sieht genau die Regel aus?

**Comment by bergjet** [comment]
<img width="1786" alt="Screenshot 2019-05-05 18 45 13" src="https://user-images.githubusercontent.com/4241968/57199037-bda65a80-6f7a-11e9-9024-5701a3a02b0b.png">

**Comment by Apollon77** [comment]
naja, deine Regel ist zu viel ... Liess mal die Infos im Forum zum Custom Skill (falls es der ist) durch. Da steht drin warum "wie" nicht vorkommt und was stattdessen da ist

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/15629/neu-iobroker-alexa-custom-skill-verf%C3%BCgbar

**Comment by bergjet** [comment]
Da steht z.B. "wie (warm es im Wohnzimmer ist)"

**Comment by Apollon77** [comment]
Mein Ansatz und der sinnvolle: sprechen, sehen was ankommt, danach die Regeln bauen

**Comment by bergjet** [comment]
Ja, stimmt, geht jetzt.
Jetzt ist mir noch was aufgefallen. Der Testsatz lautet "regnet es jetzt" Der Rückgabe Wert ist "derzeit 0" Der Wert kommt vom Netatmo Regensensor. Aber über Alexa bekomme ich keine Antwort.
![SiO3piBQ](https://user-images.githubusercontent.com/4241968/57219683-23d1c280-6ff9-11e9-9298-0a8b2a92400d.png)
<img width="1763" alt="Screenshot 2019-05-06 12 20 02" src="https://user-images.githubusercontent.com/4241968/57219733-4fed4380-6ff9-11e9-8c6d-a8464991eef7.png">

**Comment by Apollon77** [comment]
Da müsste man jetzt in Logs schauen ... an sich sollte das passen. Kommt nur da keine ANtwort oder auch generell nicht? Bei mir tut das alles

**Comment by bergjet** [comment]
Nur da. 

Von meinem iPhone gesendet
www.punz.info

**Comment by bergjet** [comment]
Wie kann ich denn in die Logs schauen?

**Comment by Apollon77** [comment]
Ich denke am besten machen wir im Forum weiter ... da können dann noch andere helfen.

**Comment by bergjet** [comment]
https://forum.iobroker.net/topic/22292/bekomme-keine-antwort/1
