### ISSUE TITLE
Wert Ausgabe von 1 auf wahr ändern

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.text2command#45]
Bei der Abfrage nach offenen Fenstern haben manche Sensoren den Wert "wahr" und andere den Wert "1".
Die Frage nach "Sind Fenster offen" ergibt dann die Antwort ja bei den einen Sensoren und 1 bei den anderen Sensoren. Kann man das irgendwie im Adapter ändern?

**Comment by GermanBluefox** [comment]
Ok. Will be implemented in 2.0.3
![image](https://user-images.githubusercontent.com/4582016/87468599-3a6ea300-c61a-11ea-99a9-27ff20d4a80a.png)

**Comment by bergjet** [comment]
Der Punkt fehlt bei mir in der Version 2.0.3
<img width="1088" alt="Screenshot 2020-07-26 15 10 24" src="https://user-images.githubusercontent.com/4241968/88479886-b5a55280-cf52-11ea-9e25-801dfe36583a.png">

**Comment by bergjet** [comment]
Keine Änderung mit 2.0.4
![Uploading Bildschirmfoto 2020-09-24 um 19.26.57.png…]()

**Comment by bergjet** [comment]
Keine Änderung mit 2.0.5
<img width="1393" alt="Bildschirmfoto 2020-09-24 um 19 26 57" src="https://user-images.githubusercontent.com/4241968/94336412-6ecfe980-ffe3-11ea-9184-b2b318e8c5bf.png">

**Comment by bergjet** [comment]
Woran kann das liegen, das bei mir der Konvertieren-Schalter nicht angezeigt wird?

**Comment by ElMorito** [comment]
Das selbe Problem habe ich auch, würde gerne alle Lichter in einem Raum an oder ausschalten.

**Comment by GermanBluefox** [comment]
Ab 2.1.8
![image](https://user-images.githubusercontent.com/4582016/154949551-2345f128-94be-4324-9e99-ad47a3938ff2.png)
