### ISSUE TITLE
Sprachauswahl ändert Triggersprache nicht

### ISSUE THREAD

**Issue by unltdnetworx** [ioBroker/ioBroker.text2command#46]
Bei einer Umstellung der Sprache in den Einstellungen einer Instanz wird zwar die Rückmeldung auf z.B. Englisch umgestellt, die vordefinierten Trigger und das Interface an sich bleiben aber in der Systemsprache.

Bei der Regel "Schalte an/aus mit Funktion" kann somit kein "Switch on..." erkannt werden, da in meinem Fall die Erkennung auf "einschalten/ausschalten/ein/aus/an/prozent" stehen bleibt.

Screenshots im [Forum](https://forum.iobroker.net/topic/23827/problem-sprachumstellung-f%C3%BCr-text2command).

**Comment by Apollon77** [comment]
Steht dioeser Triggertext wirklich so im Feld drin oder wird er nur als "Support info" angezeigt und das Feld ist eigentlich leer?

**Comment by unltdnetworx** [comment]
Der Triggertext ist so vorgegeben und würde über das Testfeld oben auch mit deutschen Wörtern auslösen. Siehe Screenshots im Forumsthread.
Bin gerade auch am Quelltext durchforsten, aber bin noch auf keinen grünen Zweig gekommen.

**Comment by unltdnetworx** [comment]
Weiterer Hinweis. Bei langsamen Geräten, etwa einem alten Smartphone, wird alles lurzt auf english angezgeit, bevor es auf deutsch wechselt.

**Comment by unltdnetworx** [comment]
Laut ioBroker Doku sollte es funktionieren:
Choosing the Language(choice from the list)-the main language which makes possible the command exchange and giving the answers;

**Comment by unltdnetworx** [comment]
Seit heute ist der Fehler scheinbar behoben. Oberfläche bleibt zwar deutsch, aber Trigger stellen sich auf englisch um.

**Comment by unltdnetworx** [comment]
Zu früh gefreut. War nur einmal möglich. Nach dem Neustart der Instanz wieder deutsche Regeln. Die bereits gespeicherte englische Regel blieb jedoch bestehen.

**Comment by unltdnetworx** [comment]
Pull-Request eingereicht. Damit würde das Backend der Instanz nun auf die gewählte Sprache umgestellt. Incl. der Triggerworte für die Regeln.

**Comment by unltdnetworx** [comment]
Erledigt mit letztem Update.
