### ISSUE TITLE
Instanz wird selbstständig doppelt ausgeführt und stützt ab

### ISSUE THREAD

**Issue by mimgeo** [ioBroker/ioBroker.text2command#54]
Ich habe nur eine Instanz installiert und alles läuft normal, bis ich Text2Command zum bearbeiten öffne. Ab da scheint sich text2command als Prozess einfach parallel erneut zu starten, sodass iobroker immer einen automatisch schließt. So lange ich das Text2Command Fenster geöffnet habe, kommt der Fehler durchgehend. Es ist dabei auch egal, ob ich text2command im separaten Tab öffne, oder im Admin-Fenster.

Siehe Log:
===================================================

  |   |   |  
-- | -- | -- | --
javascript.0 | 2020-01-16 19:35:33.816 | warn | (15473) script.js.Allgemeines.Überwachung_Adapter: telegram: Adapter text2command ---------------------------- Alive: true Connected: true
text2command.0 | 2020-01-16 19:35:23.651 | info | (30888) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.text2command, node: v10.17.0
host.raspberrypi | 2020-01-16 19:35:20.399 | info | Restart adapter system.adapter.text2command.0 because enabled
host.raspberrypi | 2020-01-16 19:35:20.398 | error | instance system.adapter.text2command.0 terminated with code 156 (156)
text2command.0 | 2020-01-16 19:35:19.811 | info | (30873) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
text2command.0 | 2020-01-16 19:35:19.807 | info | (30873) terminating
text2command.0 | 2020-01-16 19:35:19.317 | warn | (30873) Got terminate signal. Checking desired PID: 30888 vs own PID 30873
text2command.0 | 2020-01-16 19:35:19.300 | warn | (30873) Got terminate signal. Checking desired PID: 0 vs own PID 30873
host.raspberrypi | 2020-01-16 19:35:19.288 | info | instance system.adapter.text2command.0 started with pid 30888
javascript.0 | 2020-01-16 19:35:03.106 | warn | (15473) script.js.Allgemeines.Überwachung_Adapter: telegram: Adapter text2command ---------------------------- Alive: true Connected: true
text2command.0 | 2020-01-16 19:34:52.975 | info | (30873) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.text2command, node: v10.17.0
host.raspberrypi | 2020-01-16 19:34:49.246 | info | Restart adapter system.adapter.text2command.0 because enabled
host.raspberrypi | 2020-01-16 19:34:49.245 | error | instance system.adapter.text2command.0 terminated with code 156 (156)
text2command.0 | 2020-01-16 19:34:48.679 | info | (30858) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
text2command.0 | 2020-01-16 19:34:48.676 | info | (30858) terminating
text2command.0 | 2020-01-16 19:34:48.184 | warn | (30858) Got terminate signal. Checking desired PID: 30873 vs own PID 30858
text2command.0 | 2020-01-16 19:34:48.170 | warn | (30858) Got terminate signal. Checking desired PID: 0 vs own PID 30858
host.raspberrypi | 2020-01-16 19:34:48.104 | info | instance system.adapter.text2command.0 started with pid 30873
javascript.0 | 2020-01-16 19:34:31.200 | warn | (15473) script.js.Allgemeines.Überwachung_Adapter: telegram: Adapter text2command ---------------------------- Alive: true Connected: true
text2command.0 | 2020-01-16 19:34:21.071 | info | (30858) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.text2command, node: v10.17.0
host.raspberrypi | 2020-01-16 19:34:18.046 | info | Restart adapter system.adapter.text2command.0 because enabled
host.raspberrypi | 2020-01-16 19:34:18.045 | error | instance system.adapter.text2command.0 terminated with code 156 (156)
text2command.0 | 2020-01-16 19:34:17.478 | info | (30842) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
text2command.0 | 2020-01-16 19:34:17.474 | info | (30842) terminating
text2command.0 | 2020-01-16 19:34:16.979 | warn | (30842) Got terminate signal. Checking desired PID: 30858 vs own PID 30842
text2command.0 | 2020-01-16 19:34:16.965 | warn | (30842) Got terminate signal. Checking desired PID: 0 vs own PID 30842
host.raspberrypi | 2020-01-16 19:34:16.946 | info | instance system.adapter.text2command.0 started with pid 30858
javascript.0 | 2020-01-16 19:34:00.849 | warn | (15473) script.js.Allgemeines.Überwachung_Adapter: telegram: Adapter text2command ---------------------------- Alive: true Connected: true
text2command.0 | 2020-01-16 19:33:50.679 | info | (30842) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.text2command, node: v10.17.0
host.raspberrypi | 2020-01-16 19:33:46.905 | info | Restart adapter system.adapter.text2command.0 because enabled
host.raspberrypi | 2020-01-16 19:33:46.903 | error | instance system.adapter.text2command.0 terminated with code 156 (156)
text2command.0 | 2020-01-16 19:33:46.332 | info | (30827) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
text2command.0 | 2020-01-16 19:33:46.328 | info | (30827) terminating
text2command.0 | 2020-01-16 19:33:45.835 | warn | (30827) Got terminate signal. Checking desired PID: 30842 vs own PID 30827
text2command.0 | 2020-01-16 19:33:45.815 | warn | (30827) Got terminate signal. Checking desired PID: 0 vs own PID 30827
host.raspberrypi | 2020-01-16 19:33:45.791 | info | instance system.adapter.text2command.0 started with pid 30842
javascript.0 | 2020-01-16 19:33:28.881 | warn | (15473) script.js.Allgemeines.Überwachung_Adapter: telegram: Adapter text2command ---------------------------- Alive: true Connected: true
text2command.0 | 2020-01-16 19:33:18.746 | info | (30827) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.text2command, node: v10.17.0
host.raspberrypi | 2020-01-16 19:33:15.749 | info | Restart adapter system.adapter.text2command.0 because enabled
host.raspberrypi | 2020-01-16 19:33:15.748 | error | instance system.adapter.text2command.0 terminated with code 156 (156)
text2command.0 | 2020-01-16 19:33:15.189 | info | (30812) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
text2command.0 | 2020-01-16 19:33:15.185 | info | (30812) terminating
text2command.0 | 2020-01-16 19:33:14.689 | warn | (30812) Got terminate signal. Checking desired PID: 30827 vs own PID 30812
text2command.0 | 2020-01-16 19:33:14.676 | warn | (30812) Got terminate signal. Checking desired PID: 0 vs own PID 30812
host.raspberrypi | 2020-01-16 19:33:14.663 | info | instance system.adapter.text2command.0 started with pid 30827
javascript.0 | 2020-01-16 19:32:58.077 | warn | (15473) script.js.Allgemeines.Überwachung_Adapter: telegram: Adapter text2command ---------------------------- Alive: true Connected: true
text2command.0 | 2020-01-16 19:32:47.885 | info | (30812) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.text2command, node: v10.17.0
host.raspberrypi | 2020-01-16 19:32:44.623 | info | Restart adapter system.adapter.text2command.0 because enabled
host.raspberrypi | 2020-01-16 19:32:44.621 | error | instance system.adapter.text2command.0 terminated with code 156 (156)
text2command.0 | 2020-01-16 19:32:44.060 | info | (30797) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
text2command.0 | 2020-01-16 19:32:44.057 | info | (30797) terminating
text2command.0 | 2020-01-16 19:32:43.562 | warn | (30797) Got terminate signal. Checking desired PID: 30812 vs own PID 30797
text2command.0 | 2020-01-16 19:32:43.549 | warn | (30797) Got terminate signal. Checking desired PID: 0 vs own PID 30797
host.raspberrypi | 2020-01-16 19:32:43.528 | info | instance system.adapter.text2command.0 started with pid 30812
javascript.0 | 2020-01-16 19:32:27.243 | warn | (15473) script.js.Allgemeines.Überwachung_Adapter: telegram: Adapter text2command ---------------------------- Alive: true Connected: true
text2command.0 | 2020-01-16 19:32:17.088 | info | (30797) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.text2command, node: v10.17.0
host.raspberrypi | 2020-01-16 19:32:13.485 | info | Restart adapter system.adapter.text2command.0 because enabled
host.raspberrypi | 2020-01-16 19:32:13.483 | error | instance system.adapter.text2command.0 terminated with code 156 (156)
text2command.0 | 2020-01-16 19:32:12.805 | info | (30775) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
text2command.0 | 2020-01-16 19:32:12.800 | info | (30775) terminating
text2command.0 | 2020-01-16 19:32:12.303 | warn | (30775) Got terminate signal. Checking desired PID: 30797 vs own PID 30775
text2command.0 | 2020-01-16 19:32:12.288 | warn | (30775) Got terminate signal. Checking desired PID: 0 vs own PID 30775
host.raspberrypi | 2020-01-16 19:32:12.271 | info | instance system.adapter.text2command.0 started with pid 30797
web.0 | 2020-01-16 19:31:55.971 | info | (15397) <==Disconnect system.user.admin from ::ffff:192.168.1.99 flot

**Comment by mimgeo** [comment]
Zusatz: Cloud-Adapter ist bei mir nicht aktiv und damit ungenutzt.

**Comment by Apollon77** [comment]
Ja das liegt daran das die konfig im Text2command object gespeichert ist und jede konfig Änderung speichert dies und das restarted den Adapter. Leider ein Designproblem. Langsamer editieren reicht meistens.

**Comment by mimgeo** [comment]
"Langsamer editieren" reicht leider nicht. Sobald ich die Bearbeitungsseite öffne, starten die Probleme. Dabei ändere ich nichteinmal etwas.

**Comment by GermanBluefox** [comment]
Please check 2.0.1
