### ISSUE TITLE
Einheitliche deutsche Adapter Übersetzung/Bezeichnung

### ISSUE THREAD

**Issue by TeNNo2k5** [ioBroker/ioBroker.text2command#55]
Hauptsächlich stört es mich von der Ästhetik das in der Menü Leiste der Adapter (vermutlich) durch die deutsche Übersetzung **„Text -> Kommandos.0“** mit einem Zeilenumbruch dargestellt wird.

Zusätzlich ist mir aufgefallen das an unterschiedlichen Stellen verschiedene Bezeichnungen verwendet werden:

-	In der Übersicht vom Iobroker wird der Adapter mit **„Text zu Befehl“** bezeichnet.
-	Im Installationsbereich (Adapter) wird **„Text to command“** als Bezeichnung verwendet.
-	Wenn man den Adapter im Browser direkt aufruft wird innerhalb der Url **„text2command“** verwendet.

Die Frage ist muss der Adapter Name überhaupt ins deutsche Übersetzt werden? Eine einheitliche Bezeichnung z. B. **„text2command“** sollte doch allgemein verständlich sein, und wenn ein Deutscher Benutzer mit der englischen Bezeichnung nichts anfangen kann steht ja im Beschreibungsfeld _**„Dieser Adapter ermöglicht es, Text in Befehle zu konvertieren“**_

Grüße
TeNNo2k5

**Comment by GermanBluefox** [comment]
"Text zu Befehl" wird auf "Text zu Kommandos" geändert.
