### ISSUE TITLE
Sortierung Ändern (Drag/Drop) oder Gruppen

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.text2command#58]
Bei einigen Befehlen muss man die Reinfolge ändern, damit es korrekt funktioniert. Momentan muss man das mühsam über die Pfeile an der Seite machen. Es wäre super, wenn man das per Drag&Drop machen könnte.

Alternativ wäre es auch toll, wenn man die Befehle gruppieren könnte. Das würde vielen vereinfachen.

Gruppe: TV Schlafzimmer
Lauter
leiser
an/aus
..
Gruppe: Klimaanlage
an/aus
Temperatur
...
Gruppe: ...

**Comment by GermanBluefox** [comment]
Fixed with Version 2.x
