### ISSUE TITLE
V2.0 Rules nicht auswählbar/bearbeiten nicht möglich

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.text2command#61]
Beim Starten der Seite, ist eine Regel ausgewählt und erscheint auch auf der rechten Seite. Wählt man nun eine andere vorhandene an, bleibt die rechte Seite bestehen und zeigt nicht die aktuell angewählte Regel an.
Ich kann alle Regeln durch klicken ohne Aktualisierung der rechten Seite, bis auf eine Regel(DANKE). Muss immer erst die (Danke) Regel anwählen, erst dann erfolgt die Aktualisierung der rechten Seite, bei Auswahl einer anderen Regel.
![image](https://user-images.githubusercontent.com/41550245/86895472-ceb1a500-c104-11ea-8e64-3537008e749d.png)

**Comment by GermanBluefox** [comment]
Kann man was im Browser log sehen?

**Comment by crunchip77** [comment]
wenn ich einzelne Regeln durchklicke, erscheinen nur diese Zeilen
![image](https://user-images.githubusercontent.com/41550245/86956351-385b9e80-c159-11ea-8542-1f08d195e4d4.png)
diese Ausgabe erfolgt beim Seiten Laden
![image](https://user-images.githubusercontent.com/41550245/86956452-5c1ee480-c159-11ea-9bf6-429e62d8e187.png)

**Comment by GermanBluefox** [comment]
Fixed in 2.0.1

**Comment by CommanderXXL** [comment]
Ich habe das Auswahlproblem in 2.0.1 leider immer noch. Der Übersetzungsfehler ist aber gefixt. Wenn ich eine Regel auswähle, dann auf eine andere Seite im ioBroker Interface klicke und dann wieder die text2command seite aufrufe steht die vorher ausgewählte Regel drin.

**Comment by crunchip77** [comment]
Problem besteht in 2.0.1 immer noch

**Comment by jlegen** [comment]
> 
> 
> Problem besteht in 2.0.1 immer noch

ACK; sowohl Firefox als auch Chrome. 
Ausserdem - aber wohl eher "unrelated" - gibt's beim Aufruf einen 404 in der Konsole:

![grafik](https://user-images.githubusercontent.com/24507951/87151971-1c6d0f80-c2b5-11ea-981a-0490bec6ec43.png)

**Comment by GermanBluefox** [comment]
Please test latest version 2.0.2

**Comment by Black-Thunder** [comment]
Mit 2.0.2 funktioniert bei mir sowohl das Auswählen als auch Ändern der Regeln wieder. 👍

**Comment by jlegen** [comment]
...das Wesentliche scheint zu tun, ein paar Dinge scheinen aber noch zu klemmen:
- dem Geräte/ID-Selektor sind offenbar die Labels abhanden gekommen zu sein, jedenfalls heissen z.B. Buttons jetzt "RA_OK" statt "Ok", Header "ra_value" etc. 

- das mit dem "Regeln editieren" (linke Seite über "Edit"-Symbol) funktioniert bei mir irgendwie nicht wirklich. Editiere ich eine vorhandene Regel, indem ich im Editformular z.B. eine andere "Regel" auswähle (z.B. von "Schalte etwas ein/aus" nach "Frage etwas"), wird schonmal einfach mein vergebener "Name" überschrieben - unschön. 
Ändere ich diesen dann aber zurück auf den ursprünglichen, erhalte ich die Fehlermeldung "Name existiert bereits". Speichern nicht möglich. Ich breche ab, in der linken Spalte ist die Regel in der *alten* Version gelistet. Klicke dann nochmals auf diese Regel zum Editieren, erscheint im Editdialog dann aber die eben eogentlich erfolglos *geänderte* Regel...
