### ISSUE TITLE
V 2.0.0  ID Auswahl leer

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.text2command#62]
Hallo, 
1. beim auswählen der Aussentemperatur ID ist alles leer. 
2. Es kommt allgemein zu keiner Ansage.

![Screenshot (211)_LI](https://user-images.githubusercontent.com/41079106/86898760-66b18d80-c109-11ea-9444-b3e2b56a7fb9.jpg)

![Screenshot (209)](https://user-images.githubusercontent.com/41079106/86898603-37028580-c109-11ea-89ce-05016f27dcc6.png)

`

  | os: win32
-- | --
  | RAM: 7.9 GB
  | Node.js: v12.18.0
  | NPM: 6.14.4
  | JS-Controller: 3.1.6
  | Admin: 4.1.1
  | Active instances: 46
  |  
  |  

`

**Comment by Black-Thunder** [comment]
Selbes Problem hier. Nach dem Klick ins ID-Feld kommt kurz ein Dialog "Select ID" hoch und lädt für den Bruchteil einer Sekunde. Dann verschwindet der Dialog und es wird nur eine leere Seite angezeigt.

Im Browser-Log sind folgende Fehler zu sehen:
![Capture](https://user-images.githubusercontent.com/972581/86960131-5b894c80-c15f-11ea-9a3a-099421d9a666.PNG)

**Comment by GermanBluefox** [comment]
Fixed in 2.0.1
