### ISSUE TITLE
v2.0.1 Auswahl der Regel zum Editieren nicht möglich

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.text2command#65]
Egal welche Regel ich links auswähle es bleibt die erste rechts stehen.
![image](https://user-images.githubusercontent.com/39678667/87123600-6212e380-c287-11ea-8906-ba7d634f6d1f.png)

Nur wenn ich z.B. eine andere wähle, die Instanz verlasse und neu öffne, sehe ich dann die Einstellungen der zuletzt selektierten Regel.

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.text2command/issues/61

**Comment by crunchip77** [comment]
https://forum.iobroker.net/post/460525 zur besseren Veranschaulichung
