### ISSUE TITLE
v2.0.1 Testphrase erzeugt keine Ausgabe mehr

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.text2command#66]
Bis v1 wurde ein Overlay mit der Textzeile eingeblendet wenn man eine Testphrase übergeben hat.
Bei v2 wird nur die Regel, die matcht, hervorgehoben.

**Comment by GermanBluefox** [comment]
Ich verstehe nicht:
v1
![image](https://user-images.githubusercontent.com/4582016/87327986-1e450600-c535-11ea-8217-c59fe6b19a4f.png)




V2:
![image](https://user-images.githubusercontent.com/4582016/87328047-36b52080-c535-11ea-904b-419517b780d4.png)

Geht doch, oder?

**Comment by Diginix** [comment]
Zumindest bei "Frage etwas" kam bei Eingabe eines Schlüsselwortes und Klick auf den Playbutton in v1 ein Overlay im orangefarbenen markierten Bereich mit dem kompletten ausformulierten Text inkl Variablenwerten usw.
Parallel wurde er manchmal bei mir auch am PC Lautsprecher ausgegeben.

![image](https://user-images.githubusercontent.com/39678667/87341413-e1cfd500-c549-11ea-8b13-003a407fa192.png)

**Comment by GermanBluefox** [comment]
Wird in 2.0.3 implementiert.
