### ISSUE TITLE
Command are not properly recognized

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.text2command#7]
I have two commands to switch on or off the light in the livng room.
See screenshot
![bild1](https://cloud.githubusercontent.com/assets/11745094/24572308/d28be590-1677-11e7-817c-82b5abd04c42.jpg)
When I say "Licht im Wohnzimmer an" then text2command understands
"nicht im Wohnzimmer an". However it switches the light on, which is wrong in my opinion, because "Licht" was not recognized, so why was the rule executed?:
`sayit.0	2017-04-01 01:03:41.021	info	saying: Eingeschaltet
hm-rpc.0	2017-04-01 01:03:41.016	info	setValue ["HEQ0074086:2","STATE",true] BOOL
hm-rpc.0	2017-04-01 01:03:41.004	info	setValue ["HEQ0074086:2","STATE",true] BOOL
text2command.0	2017-04-01 01:03:40.982	info	Control ID hm-rpc.0.HEQ0074086.2.STATE with : true
text2command.0	2017-04-01 01:03:40.981	info	processText: "Computer nicht im Wohnzimmer an"`

Next issue is, that it does not choose the proper rule.
When I say "Licht im Wohnzimmer aus", it should choose the rule "Wohnzimmer/Licht/aus/ausschalten", but it still uses "Wohnzimmer/Licht/ein/an/einschalten":
`sayit.0	2017-04-01 01:05:50.122	info	saying: Eingeschaltet
hm-rpc.0	2017-04-01 01:05:50.092	info	setValue ["HEQ0074086:2","STATE",true] BOOL
hm-rpc.0	2017-04-01 01:05:50.074	info	setValue ["HEQ0074086:2","STATE",true] BOOL
text2command.0	2017-04-01 01:05:50.062	info	Control ID hm-rpc.0.HEQ0074086.2.STATE with : true
text2command.0	2017-04-01 01:05:50.061	info	processText: "Computer Licht im Wohnzimmer aus"
text2command.0	2017-04-01 01:05:50.060	info	Control ID hm-rpc.0.HEQ0074086.2.STATE with : true
text2command.0	2017-04-01 01:05:50.059	info	processText: "Computer Licht im Wohnzimmer aus"`

**Comment by unltdnetworx** [comment]
Hallo,
maybe too late, but for your information.
This is not an issue, your rules are simply wrong. Every word devided by "/" is an optional statement. So only one of them has to be in the sentence.

For example if you say "Ist ein Fenster im Wohnzimmer offen?" the light will start also, because "Wohnzimmer" is triggered and the first rule is activated. "Lights on".

So the issue can be closed.

**Comment by derrapf** [comment]
Thanks. Yes. Little bit late. I use Alexa now.
