### ISSUE TITLE
Alexa die Verarbeitung ist nicht möglich.

### ISSUE THREAD

**Issue by ma-gu-16** [ioBroker/ioBroker.text2command#70]
Alexa sagt ständig die Verarbeitung sei nicht möglich. 
Laut dem Log sowie der tooltip im tex2command, scheint die Frage gepasst haben. 

Nur Alexa spricht die Antwort nicht aus, sondern sagt Verarbeitung sei nicht möglich. 

![image](https://user-images.githubusercontent.com/22169074/94167352-b3953c80-fe8c-11ea-8be9-a26086d6f8a0.png)

Hab Version 2.0.3 vom Adapter.

**Comment by Apollon77** [comment]
Timeout vom externl processor ... also wie verarbeitest Du die Regeln? Da kommt kein ergebnis ... steht doch im Log

**Comment by Apollon77** [comment]
Ergo: Deine Antwort dauert zu lange

**Comment by Apollon77** [comment]
Doku lesen bitte!

**Comment by ma-gu-16** [comment]
`on({id: 'javascript.0.marc.textProcessorAlexa', ack: false, change: 'any'}, function (obj) {
        var task = JSON.parse(obj.state.val);

        if(task.command = 'askDevice status'){
            setState('javascript.0.marc.textAnswerAlexa', 'test test', true);
        }
    
});`

naja kann mir nicht vorstellen das dies so lange geht? Ich mach ja im Grund nix ?
