### ISSUE TITLE
text2command Seite lässt sich nicht öffnen

### ISSUE THREAD

**Issue by Gre4tOne** [ioBroker/ioBroker.text2command#73]
Alle Adapter aktuell
Node.js
v14.13.0 (hat mit v 10.xx auch nicht funktioniert daher update)
NPM
6.14.8

Benutze MacOS (Chrome, Firefox und Safari kann Seite nicht öffnen  - bzw. bleibt leer)

**Comment by Apollon77** [comment]
Zeigtdie Browser Konsole irgendinen Fehler an? Welche Admin version?

**Comment by Gre4tOne** [comment]
Admin v 4.1.8

Browser Konsole:

Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen. jquery-3.2.1.min.js:4
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. ace.js:1
Passwort-Felder sind auf einer unsicheren (http://) Seite vorhanden. Dies ist ein Sicherheitsrisiko, durch das Zugangsdaten gestohlen werden können.
192.168.178.xxx:8081
Einige Cookies verwenden das empfohlene "sameSite"-Attribut inkorrekt. 5
Das Cookie “io” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite socket.io
Das Cookie “io” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite socket.io
Das Cookie “io” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite socket.io
Das Cookie “io” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite socket.io
Das Cookie “io” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite socket.io
"tree": {"en": "tree", "de": "tree", "ru": "tree", "pt": "tree", "nl": "tree", "fr": "tree", "es": "tree", "pl": "tree", "it": "tree", "zh-cn": "tree"}, translate.js:24
Fancytree@1 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead. jquery.fancytree-all.js:113
iobroker.text2command@2.0.5 using theme "colored" index.js:17:8

██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
instrument.ts:129:35
Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters instrument.ts:129:35
Help us to create open source project with reactJS! instrument.ts:129:35
See you :) instrument.ts:129:35
Einige Cookies verwenden das empfohlene "sameSite"-Attribut inkorrekt. 2
Object { rules: (18) […], sayitInstance: "", language: "", processorId: "", processorTimeout: 1000, writeEveryAnswer: false }
instrument.ts:129:35
Object { currentRules: [], isOpen: false, isEdit: false, selectedRule: null, unsavedRules: {}, ready: false, isLeftBarOpen: false }
instrument.ts:129:35
Uncaught (in promise) TypeError: s is undefined
    s Layout.js:337
    getDataFromConfig Layout.js:331
Layout.js:337:28

​

**Comment by Gre4tOne** [comment]
?

**Comment by daniel-lo** [comment]
Bei mir verschwindet die Oberfläche auch .. nach einer Neuinstallation des Adapters ein Mal da .. nichts im Log.

**Comment by W0RSCHD** [comment]
Habe das gleiche Problem, von jetzt auf nachher lässt sich der Kommandos Tab nicht mehr öffnen, es erscheint einfach nichts.

NodeJS 14.18.1
Admin 5.2.3
Js 3.3.22

**Comment by Apollon77** [comment]
Und was sagt die Browser error console?

**Comment by W0RSCHD** [comment]
Object { rules: [], isOpen: false, isEdit: false, isCopy: false, selectedRule: null, unsavedRules: {}, ready: false, isLeftBarOpen: false }
instrument.ts:129:35
Uncaught (in promise) TypeError: s is undefined
    s Layout.js:376
    bt Layout.js:370
Layout.js:376:28
Service worker event waitUntil() was passed a promise that rejected with 'Error: bad-precaching-response :: [{"url":"https://192.168.178.105:8081/adapter/text2command/index.html?__WB_REVISION__=dcffee691a65276f5dd9a0eaab3f9d2e","status":404}]'. workbox-core.prod.js:1:240
Object { rules: [], isOpen: false, isEdit: false, isCopy: false, selectedRule: null, unsavedRules: {}, ready: false, isLeftBarOpen: false }
instrument.ts:129:35
Error: Promised response from onMessage listener went out of scope

**Comment by W0RSCHD** [comment]
Kann man damit was anfangen oder den Fehler eingrenzen?
