### ISSUE TITLE
Wert Ausgabe von 1 auf wahr ändern V2.07

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.text2command#78]
Bei mir fehlt dieser Schalter in der V2.07
<img width="2068" alt="Bildschirmfoto 2020-12-30 um 10 29 58" src="https://user-images.githubusercontent.com/4241968/103342589-2ca6c000-4a8a-11eb-8bf3-290effcf3c46.png">

**Comment by bergjet** [comment]
Problem besteht noch immer.

**Comment by GermanBluefox** [comment]
Und bei 2.1.7?

**Comment by bergjet** [comment]
Dieser Schalter ist nun da. Danke.
