### ISSUE TITLE
Only switching on but not turning off in telegram

### ISSUE THREAD

**Issue by MasterMik** [ioBroker/ioBroker.text2command#79]
Hi,

I'm using text2command together with telegram. There I made a small menü to turn on/off some sockets.
![grafik](https://user-images.githubusercontent.com/16462739/106371717-dd44ff80-6367-11eb-811a-5c2b59a7c04d.png)

It doesn't metter which button i push, e.g. 4-on or 4-off, the output is always the same:
![grafik](https://user-images.githubusercontent.com/16462739/106371779-ca7efa80-6368-11eb-8659-c1f4dd8862d2.png)

Here my setup in text2command:
![grafik](https://user-images.githubusercontent.com/16462739/106371807-25b0ed00-6369-11eb-82e0-bc8b42e51088.png)
![grafik](https://user-images.githubusercontent.com/16462739/106371810-2b0e3780-6369-11eb-804d-13dcec9be124.png)

and the java script:
![grafik](https://user-images.githubusercontent.com/16462739/106371825-555ff500-6369-11eb-8222-a1b16a6f0220.png)

text2command adapter version: 2.0.7
Telegram adpter version: 1.6.0

Is this a bug?

**Comment by EddyDsSmartHome** [comment]
Habe das gleiche Problem, hast du eine Lösung gefunden?
Meine alten Regeln funktionieren ohne Probleme (ON/OFF) aber wenn ich eine neue Regel erstelle geht es nicht.

**Comment by MasterMik** [comment]
Hi, habe bis jetzt nichts herausgefunden, werde aber deinen "Trick" ausprobieren.
