### ISSUE TITLE
Text2Command is restarted after recognizing

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.text2command#8]
I have the following rule now:
![bild2](https://cloud.githubusercontent.com/assets/11745094/24572462/29b6bfec-1679-11e7-9291-be9f3ff9fab7.jpg)
Text2Command recognizes the command "Licht im Wohnzimmer aus" but the issues is:
- it switches it on instead of off
- the it crashed obviously and gets restarted continuoulsy
`host.ioBroker-Pi2	2017-04-01 01:16:56.254	error	instance system.adapter.text2command.0 terminated with code 7 (Adapter already running)
host.ioBroker-Pi2	2017-04-01 01:16:53.386	info	instance system.adapter.text2command.0 started with pid 28145
host.ioBroker-Pi2	2017-04-01 01:16:23.347	info	Restart adapter system.adapter.text2command.0 because enabled
host.ioBroker-Pi2	2017-04-01 01:16:23.346	error	instance system.adapter.text2command.0 terminated with code 7 (Adapter already running)
host.ioBroker-Pi2	2017-04-01 01:16:20.523	info	instance system.adapter.text2command.0 started with pid 28099
host.ioBroker-Pi2	2017-04-01 01:15:50.486	info	Restart adapter system.adapter.text2command.0 because enabled
host.ioBroker-Pi2	2017-04-01 01:15:50.485	error	instance system.adapter.text2command.0 terminated with code 7 (Adapter already running)
host.ioBroker-Pi2	2017-04-01 01:15:47.630	info	instance system.adapter.text2command.0 started with pid 28080
sayit.0	2017-04-01 01:15:42.977	info	saying: Eingeschaltet
hm-rpc.0	2017-04-01 01:15:42.970	info	setValue ["HEQ0074086:2","STATE",true] BOOL
text2command.0	2017-04-01 01:15:42.951	info	Control ID hm-rpc.0.HEQ0074086.2.STATE with : true
text2command.0	2017-04-01 01:15:42.949	info	processText: "Computer Licht im Wohnzimmer ausschalten"
sayit.0	2017-04-01 01:15:20.595	info	saying: Eingeschaltet
hm-rpc.0	2017-04-01 01:15:20.589	info	setValue ["HEQ0074086:2","STATE",true] BOOL
text2command.0	2017-04-01 01:15:20.573	info	Control ID hm-rpc.0.HEQ0074086.2.STATE with : true
text2command.0	2017-04-01 01:15:20.571	info	processText: "Computer Licht im Wohnzimmer aus"`

After I removed the last rule the adapter stops to restart

**Comment by GermanBluefox** [comment]
Still actual?
