### ISSUE TITLE
Adapter Webseiten bei mehreren text2command Instanzen

### ISSUE THREAD

**Issue by actionbyte** [ioBroker/ioBroker.text2command#83]
Hallo,

ich habe mehrere Instanzen vom text2command Adapter am laufen, bekomme aber bei jeder Instanz die gleiche Adapter Webseite beim Aufruf hinter der Instanzanzeige angezeigt.
Ich möchte aber für jede Instanz eine eigene Webseite mit separaten Befehlen verwalten können.
Hintergrund: ich habe drei Telegramm Adaptern je eine t2c Instanz zugewiesen und möchte mit dem gleichen Befehl ein anderes Script starten. Wenn aber hinter jeder t2c Instanz die gleiche Webseite ist, wird immer mit dem gleichen Befehl ein bestimmtes Script gestartet, ich kann also nicht unterscheiden von welchem Telegramm Adapter der Aufruf kam um eine individuelle Ausführung zu starten.

**Comment by EddyDsSmartHome** [comment]
Hi, evtl. etwas spät aber einfach ein " ?instance=1 " dahinter schreiben.

z.B.:
https://192.168.178.3:8081/adapter/text2command/tab.html?instance=1
