### ISSUE TITLE
enum.functions should be predefined with defaults

### ISSUE THREAD

**Issue by lubeda** [ioBroker/ioBroker.text2command#9]

**Comment by Apollon77** [comment]
Plese provide more informatuions on your request

**Comment by GermanBluefox** [comment]
I do not understand it too.

2017-05-17 21:45 GMT+02:00 Ingo Fischer <notifications@github.com>:

**Comment by lubeda** [comment]
In my installlation the enums.rooms was empty at installation. Then my fhem adapter filled with the rooms from my fhem system. 
But the enum.functions was empty.  So i had to fill the enum.functions manually with the values as decribed in https://github.com/ioBroker/ioBroker.text2command/blob/master/README.md

I thing it would be nice to have the rooms and the functions enums with default values during activation of this adapter.

Auf Deutsch: Bei der Installation waren keine Funtionen und Räume vordefiniert. Die Räume wurden durch meinen FHEM-Adapter gefüllt aber die Funktionen blieben leer. Ich muss also für den text2command Adapter die Funktionen manuell ein tippen.

Bei den Räumen und Funktionen könnte man doch systemseitig Werte vorbelegen...
