### ISSUE TITLE
Erweiterung mehrere Objekte einbinden

### ISSUE THREAD

**Issue by ohle64** [ioBroker/ioBroker.text2command#95]
Os: linux(ubuntu1804); Node(js): 12.22.1; NPM: 6.14.12; js-controller: 3.3.11; admin: v5.1.7(ReactUI aktiv)
Betrifft: v2.1.0

Beim Anlegen von Fragen kann z.Z. nur eine Objekt-ID mit %s und Einheit %u ausgewählt werden. Die Frage nach z.B. wie warm ist es im Bad könnte dann auch die Luftfeuchte mit ausgegeben werden z.B. %s1 und %u1.

**Comment by GermanBluefox** [comment]
implemented in 2.1.8
![image](https://user-images.githubusercontent.com/4582016/154958008-80baed7d-07cb-4bbd-b10e-8aef9ef0e792.png)

**Comment by ohle64** [comment]
super, Besten Dank
